/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Guild: () => import('#controllers/guild_controller'),
  Home: () => import('#controllers/home_controller'),
  Login: () => import('#controllers/login_controller'),
  Queries: () => import('#controllers/queries_controller'),
  Storage: () => import('#controllers/storage_controller'),
}
