/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnnouncementChannelSchema extends BaseModel {
  static $columns = ['categoryId', 'channelId', 'createdAt', 'guildId', 'id', 'mentionRoleId', 'updatedAt'] as const
  $columns = AnnouncementChannelSchema.$columns
  @column()
  declare categoryId: number | null
  @column()
  declare channelId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare guildId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mentionRoleId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'guildId', 'id', 'name', 'queryNotificationMentionRoleId', 'tags', 'updatedAt'] as const
  $columns = BookCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare guildId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare queryNotificationMentionRoleId: string | null
  @column()
  declare tags: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'description', 'id', 'publishedAt', 'storageAmount', 'title', 'updatedAt', 'url'] as const
  $columns = BookSchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare storageAmount: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string | null
}

export class GroupRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'guildId', 'id', 'roleId', 'updatedAt'] as const
  $columns = GroupRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare guildId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GuildConfigSchema extends BaseModel {
  static $columns = ['adminRoleId', 'backendRoleId', 'createdAt', 'id', 'queryNotificationChannelId', 'queryNotificationMentionRoleId', 'storageAlertThreshold', 'updatedAt'] as const
  $columns = GuildConfigSchema.$columns
  @column()
  declare adminRoleId: string | null
  @column()
  declare backendRoleId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queryNotificationChannelId: string | null
  @column()
  declare queryNotificationMentionRoleId: string | null
  @column()
  declare storageAlertThreshold: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuerySchema extends BaseModel {
  static $columns = ['bookId', 'createdAt', 'id', 'updatedAt', 'userId', 'userName'] as const
  $columns = QuerySchema.$columns
  @column()
  declare bookId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare userName: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'guilds', 'id', 'lastGuildId', 'nickname', 'token', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare guilds: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastGuildId: string | null
  @column()
  declare nickname: string
  @column()
  declare token: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
